[package]
name = "bandit"
version = "0.1.0"
authors = ["<stdev17@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.0"
tokio = { version = "0.2", features = ["fs"] }